[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta:__legacy__"

# Allow pytest to run suite without explicit pip install [package].
[tool.pytest.ini_options]
pythonpath = ["."]
